# -*- coding: utf-8 -*-
"""Agenticai_july_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zarrrlW0A8I0Cb1N4v1QZiVn8eYZ4nuU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/Churn_Modelling.csv")

df.head()

df.tail()

df.shape

df.describe(include="all")

df=df.drop(columns=["RowNumber","CustomerId","Surname"])

df.hist(figsize=(10,10))
plt.show()

df.isnull().sum()

df=pd.get_dummies(df,columns=["Geography","Gender"])

df.head()

Y=df[["Exited"]]
X=df.drop("Exited",axis=1)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,Y_train)

log_reg.score(X_train,Y_train)

log_reg.score(X_test,Y_test)

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(max_depth=5)
dtc.fit(X_train,Y_train)

dtc.score(X_train,Y_train)

dtc.score(X_test,Y_test)

